runtime: custom
env: flex
service: default

# Override Docker CMD so App Engine uses the runtime-provided PORT.
# entrypoint: /bin/sh -c "uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8080}"

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

readiness_check:
  path: "/health/ready"
  check_interval_sec: 10
  timeout_sec: 4
  failure_threshold: 3
  success_threshold: 2

liveness_check:
  path: "/health/live"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# App Engine URL: https://alfahadh-practice.el.r.appspot.com
# Cloud SQL connection name: alfahadh-practice:us-central1:python-test
# Update DB user/password/db name below if they differ in your Cloud SQL setup.
env_variables:
  PROJECT_NAME: "K8s Learning Order Platform"
  API_PREFIX: "/api"
  ENVIRONMENT: "gae"
  LOG_LEVEL: "INFO"
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  SECRET_KEY: "CHANGE_ME_STRONG_SECRET"
  DATABASE_URL: "postgresql+psycopg2://app_user:app_password@/app_db?host=/cloudsql/alfahadh-practice:us-central1:python-test"
  REDIS_URL: "redis://default:yPsSqjxk1HCIN67kWe3DZvCdw9Vw84a6@redis-14642.c259.us-central1-2.gce.cloud.redislabs.com:14642/0"
  CELERY_BROKER_URL: "redis://default:yPsSqjxk1HCIN67kWe3DZvCdw9Vw84a6@redis-14642.c259.us-central1-2.gce.cloud.redislabs.com:14642/0"
  CELERY_RESULT_BACKEND: "redis://default:yPsSqjxk1HCIN67kWe3DZvCdw9Vw84a6@redis-14642.c259.us-central1-2.gce.cloud.redislabs.com:14642/0"
  DEFAULT_ADMIN_EMAIL: "admin@k8s-learning.local"
  DEFAULT_ADMIN_PASSWORD: "admin12345"
  CORS_ORIGINS: "https://alfahadh-practice.el.r.appspot.com"

beta_settings:
  cloud_sql_instances: "alfahadh-practice:us-central1:python-test"
