runtime: custom
env: flex
service: default

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

readiness_check:
  path: "/health/live"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 5
  success_threshold: 2
  app_start_timeout_sec: 600

liveness_check:
  path: "/health/live"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 4
  success_threshold: 2

env_variables:
  PROJECT_NAME: "K8s Learning Order Platform"
  API_PREFIX: "/api"
  ENVIRONMENT: "gae"
  LOG_LEVEL: "INFO"
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  SECRET_KEY: "CHANGE_ME_STRONG_SECRET"

  # IMPORTANT: Password '#' encoded as %23
  DATABASE_URL: "postgresql+psycopg2://postgres:Passwd123%23@/postgres?host=/cloudsql/alfahadh-practice:us-central1:python-test"

  REDIS_URL: "redis://default:yPsSqjxk1HCIN67kWe3DZvCdw9Vw84a6@redis-14642.c259.us-central1-2.gce.cloud.redislabs.com:14642/0"
  CELERY_BROKER_URL: "redis://default:yPsSqjxk1HCIN67kWe3DZvCdw9Vw84a6@redis-14642.c259.us-central1-2.gce.cloud.redislabs.com:14642/0"
  CELERY_RESULT_BACKEND: "redis://default:yPsSqjxk1HCIN67kWe3DZvCdw9Vw84a6@redis-14642.c259.us-central1-2.gce.cloud.redislabs.com:14642/0"

  DEFAULT_ADMIN_EMAIL: "admin@k8s-learning.local"
  DEFAULT_ADMIN_PASSWORD: "admin12345"

  CORS_ORIGINS: "https://alfahadh-practice.el.r.appspot.com"

beta_settings:
  cloud_sql_instances: "alfahadh-practice:us-central1:python-test"
