name: k8s-learning-ci-cd

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint
        run: ruff check app tests

      - name: Test
        run: pytest -q tests

  build-and-push:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: lint-test
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_BACKEND: ghcr.io/${{ github.repository_owner }}/k8s-learning-backend
      IMAGE_FRONTEND: ghcr.io/${{ github.repository_owner }}/k8s-learning-frontend
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.IMAGE_BACKEND }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_BACKEND }}:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.IMAGE_FRONTEND }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_FRONTEND }}:latest

  deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: build-and-push
    env:
      IMAGE_BACKEND: ghcr.io/${{ github.repository_owner }}/k8s-learning-backend
      IMAGE_FRONTEND: ghcr.io/${{ github.repository_owner }}/k8s-learning-frontend
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.31.0"

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > ~/.kube/config

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/namespaces/namespace.yaml
          kubectl apply -f k8s/rbac/backend-rbac.yaml
          kubectl apply -f k8s/backend/configmap.yaml
          kubectl apply -f k8s/backend/secret.yaml
          kubectl apply -f k8s/postgres/pvc.yaml
          kubectl apply -f k8s/postgres/service.yaml
          kubectl apply -f k8s/postgres/statefulset.yaml
          kubectl apply -f k8s/redis/service.yaml
          kubectl apply -f k8s/redis/deployment.yaml
          kubectl apply -f k8s/backend/deployment.yaml
          kubectl apply -f k8s/backend/worker-deployment.yaml
          kubectl apply -f k8s/backend/service.yaml
          kubectl apply -f k8s/backend/hpa.yaml
          kubectl apply -f k8s/frontend/deployment.yaml
          kubectl apply -f k8s/frontend/service.yaml
          kubectl apply -f k8s/monitoring/prometheus.yaml
          kubectl apply -f k8s/monitoring/grafana.yaml
          kubectl apply -f k8s/ingress/ingress.yaml

      - name: Update images with versioned tags
        run: |
          kubectl -n k8s-learning set image deployment/backend-api backend=${IMAGE_BACKEND}:${IMAGE_TAG}
          kubectl -n k8s-learning set image deployment/backend-worker worker=${IMAGE_BACKEND}:${IMAGE_TAG}
          kubectl -n k8s-learning set image deployment/frontend-web frontend=${IMAGE_FRONTEND}:${IMAGE_TAG}
          kubectl -n k8s-learning rollout status deployment/backend-api --timeout=120s
          kubectl -n k8s-learning rollout status deployment/backend-worker --timeout=120s
          kubectl -n k8s-learning rollout status deployment/frontend-web --timeout=120s

